version: '3'

services:
  web:
    image: brian214/personal-site-web:latest
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static_volume:/var/www/brianis.me/static
      - ./media:/var/www/brianis.me/media
      - ./data:/app/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/brianis.me/static:ro
      - ./media:/var/www/brianis.me/media:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web


  nginx_prometheus_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: --nginx.scrape-uri=http://nginx:8080/stub_status
  

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana-storage:/var/lib/grafana
  

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  
volumes:
  static_volume:
  grafana-storage:
