version: '3'

services:
  web:
    image: brian214/personal-site-web:latest
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static_volume:/var/www/brianis.me/static
      - ./data:/app/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/brianis.me/static:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  
volumes:
  static_volume:
