# Generated by Django 4.2.7 on 2023-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
    ]
