# Generated by Django 4.2.7 on 2023-11-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_repo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
