# Generated by Django 4.2.7 on 2024-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_tag_id_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_name',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='black.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
