name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create RSA Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem

      - name: Connect and Deploy
        run: |
          scp -i ~/.ssh/key.pem nginx/nginx.conf ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app/nginx/
          scp -i ~/.ssh/key.pem docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app/
          ssh -i ~/.ssh/key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          cd app
          echo "${{ secrets.SECRET_KEY }}" > .env
          docker-compose down
          docker-compose up -d
          exit
