name: Build and Deploy to EC2

on:
  push:
    branches:
      main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push django app
        uses: docker/build-push-action@v5
        with:
          context: personalsite/
          file: personalsite/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/personal-site-web:latest

      - name: Build and push fluentd
        uses: docker/build-push-action@v5
        with:
          context: fluentd/
          file: fluentd/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fluentd

      - name: Create RSA Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem

      - name: Copy configuration files.
        run: |
          scp -o 'StrictHostKeyChecking no' -r -i ~/.ssh/key.pem config/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app/
          scp -o 'StrictHostKeyChecking no' -i ~/.ssh/key.pem docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app/

      - name: Connect and deploy.
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/app
            echo "${{ secrets.SECRET_KEY }}" > .env
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/personal-site-web:latest
            docker-compose down
            docker-compose up -d
            docker exec app-web-1 python manage.py collectstatic --noinput