name: Deploy to AWS EC2

on:
  push:
    branches:
      main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create RSA Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem

      - name: Copy configuration files.
        run: |
          scp -o 'StrictHostKeyChecking no' -i ~/.ssh/key.pem nginx/nginx.conf ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app/nginx/
          scp -o 'StrictHostKeyChecking no' -i ~/.ssh/key.pem docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app/

      - name: Connect and deploy.
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/app
            echo "${{ secrets.SECRET_KEY }}" > .env
            docker-compose down
            docker-compose up -d